[package]
name = "warfare"
version = "0.1.0"
edition = "2018"

[dependencies]
bevy = "0.5"
bevy_egui = "0.7"
bevy_tilemap = "0.4.0"

rand = "0.8.4"
rand_pcg = "0.3.1"

noise = "0.7.0"

anyhow = "1.0.38"
thiserror = "1.0.23"