[package]
name = "warfare"
version = "0.1.0"
edition = "2018"

[dependencies]
# bevy-related crates
bevy = "0.5"
bevy_egui = "0.7"
bevy_tilemap = "0.4.0"

# noise for map generation
rand = "0.8.4"
rand_pcg = "0.3.1"
noise = "0.7.0"

# loggin and error handling
log = "0.4.14"
anyhow = "1.0.38"
thiserror = "1.0.23"
pretty_env_logger = "0.4.0"